rec.TW.x.hdr.Config

ans = 

  struct with fields:

                                       AFLin: 2
                                       AFPar: 1
                            AcceleratedAlgos: 751
                 AdditionalImageDimensionAVE: []
                  AdditionalNoiseScaleFactor: 1
                                    AdjPdsID: 741
                                     AdjType: []
                   AllowImaScansNotOnPatGrid: []
                         AlsoWarnOnInitValue: 1
                        AlwaysImplicitFilter: 4
                      ApplyMaxwellCorrection: []
                  ApplyStaticFieldCorrection: []
                                  Arrhythmia: [0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 … ] (1×32 double)
                           ArtifactReduction: []
                            AutoLoadInViewer: 1
                              AutoLoadViewer: []
                     AutoPixelRepresentation: []
                                   AutoScale: []
                                 AverageMode: 1
                                    Averages: 1
                BandwidthPerPixelPhaseEncode: []
                              BaseResolution: 288
                                  BolusAgent: []
                                BorderPreset: -1
                                    CPUCount: 20
                               CalcSNRValues: []
                         CalcTReff4AllSlices: []
                          ChannelDiscardMode: 1
                       ChannelMixingMatrixID: 741
               ChannelMixingMatrixNamePrefix: 'ChannelMixingMatrix_'
                           ChannelMixingMode: 1
                              ChannelScaling: 1
                    CheckMeasStatusInfo_MoCo: []
                               CoilElementID: []
                          ColSlopeLenFromSeq: -1
                      ConditionalPatchAlways: []
                         ConfigColSlopeAhead: []
                        ConfigColSlopeBehind: []
                         ConfigLinSlopeAhead: []
                        ConfigLinSlopeBehind: []
                         ConfigParSlopeAhead: []
                        ConfigParSlopeBehind: []
                       ContinuousTriggerTime: []
                         ContrastBolusVolume: []
                                 ControliPAT: []
                               Convert2Short: 1
                   CutOffRelative2BitsStored: []
                                 DATATHREADS: []
                                        DAve: 1
                                       DFree: []
                    DICOMAcquisitionContrast: 'T2_STAR'
                            DICOMImageFlavor: []
                                     DataSrc: 4
                         DcmEngineConfigRoot: '%DICOM_ENGINE_CONFIG_DIR%'
               DcmEngineDefaultFrameBoundary: 100
            DcmEngineEnablePresentationState: 1
                     DcmEngineOutputFormatID: 1
              DcmEnginePresentationStateMode: 1
                               DeactivateMKL: []
                     DeactivateNoiseMapCache: []
                           DebugDumpPathName: 'C:/MedCom/Temp/'
                         DeclareAVEDimension: []
                           DelegateAcqEndFlg: []
                             DependentFileId: []
                           DisableLinesRecon: []
                          DisableMeasIdCheck: []
                               DoNoisePreset: []
                                   DoNormOri: 1
                                DumpFileName: []
                                 DynamicNCha: []
                                     EXECUTE: 1
                         EdgeEnhancementOnly: []
                            EllipFilterWidth: 0.0200
                          EllipticalFilterOn: 1
                                  EndMeasUid: []
                                EndMultiStep: []
                                    EndStudy: []
                              EnhancingLevel: 3
                     ErrorOnNotPaFTedData43D: 1
                               EvalInfoMask1: []
                               EvalInfoMask2: []
                                ExamComposer: []
                                ExamDataRole: []
                               ExamMemoryUID: 'c6244c5f0feb4979b9356d650290029c'
                                     ExclDim: 391
                      ExclDim4ScanMiniHeader: 135
                         ExclDimFirstSliceNo: []
                   ExclDimKSpaceCentreLineNo: []
                          ExclDimLinElliScan: []
                          ExclDimParElliScan: []
                    ExclDimPmuTimeOfZeroLine: []
                                ExclDimTReff: []
                     ExclDimTimeOfCenterScan: []
                      ExclDimTimeOfFirstScan: []
                       ExclDimTimeOfLastScan: []
                ExclDimTriggerTimeCenterLine: []
                    ExportFilterCoefficients: []
                              ExportGFactors: []
                        ExportReadoutDetails: []
                                      FTMode: 1
                               FeatureToggle: []
                                  FilterAlgo: 2
                                  FilterMode: 7
                         FinalCheck4Counters: 1
                            ForceSkipDisplay: []
                      ForwardChunkOfAverages: 1
                                ForwardSrcAs: []
                            FrameOfReference: '1.3.12.2.1107.5.2.50.176289.1.20241024184437525.0.0.4984'
                                       GROUP: 'Calculation'
                      GlobalImageScaleFactor: 117.1014
                           GlobalTablePosCor: []
                           GlobalTablePosSag: []
                           GlobalTablePosTra: -16
                                GradientFile: []
                        GradientFileAsString: []
                                 GrappaPSize: 4
                              GrappaSegments: 5
                            HighDynamicRange: []
                                    HighPrio: []
                          Hold1stOrientation: []
                   IDEdgeEnhancementStrength: 3
                         IDSmoothingStrength: 3
                               IceConfigMask: 32768
                              IceControlMask: 142
                          IceProgramCtrlMsk2: []
                          IceZeroFillingMode: []
                          IgnoreCMdoneInCtrl: []
                   IgnoreMatrixRetrieveError: []
                    IgnoreRefScansOutOfRange: []
                              ImaScaleFactor: 1
                                ImageColumns: 288
                             ImageDumpFormat: []
                                  ImageLines: 256
                        ImageNumberingStatus: 65535
                              ImagesExpected: []
                             ImgTypeHandling: []
                           ImplicitFiltering: []
                             ImprovedWeights: []
                                 InplaceAccu: 1
                          InstanceName4Debug: []
                           IntensityCorrMask: []
                         InverseChannelScale: []
                          InverseScaleFactor: 1
                       InversionTimeRequired: []
               InversionTimeSetToTriggerTime: []
                                        Is3D: 1
                           Is3DMargosianAlgo: []
                               IsBookkeeping: []
                            IsCardiacTrigger: []
                          IsChannelReduction: []
                        IsDimensionAveraging: []
                                IsDumpImages: []
                             IsDumpParamInfo: []
                     IsElliScanningRawFilter: []
                             IsIPatCounterOn: 1
                              IsImaCounterOn: []
                          IsInlineProcessing: 1
                                     IsMDSOn: []
                             IsMargosianAlgo: []
                            IsRawFiltEnabled: []
                                  IsRealtime: []
                        IsRefScan3DFiltering: []
                             IsRefScanFilter: 1
                                IsRetroRecon: []
                            IsSaveUnfiltered: []
                       IsSharedPhasesTrigger: []
                                IsSimSetting: []
                               IsSincEnabled: []
                            IsSingletonRecon: []
                            IsSlopeReplaceOn: []
                     IsStoreRefScans4AllReps: []
                            IsTOFSlabOverlap: []
                             IsTReffRequired: []
                              KxFilterLength: 576
                              KyFilterLength: 129
                                       LFree: []
                          LinSlopeLenFromSeq: -1
                               LoopLengthAve: -1
                               LoopLengthEco: -1
                               LoopLengthIda: -1
                               LoopLengthIdb: -1
                               LoopLengthIdc: -1
                               LoopLengthIdd: -1
                               LoopLengthIde: -1
                               LoopLengthPar: 48
                               LoopLengthPhs: -1
                               LoopLengthSet: -1
                               LoopLengthSlc: -1
                                LoopStartAve: []
                                LoopStartEco: []
                                LoopStartIda: []
                                LoopStartIdb: []
                                LoopStartIdc: []
                                LoopStartIdd: []
                                LoopStartIde: []
                                LoopStartPar: 2
                                LoopStartPhs: []
                                LoopStartRep: []
                                LoopStartSet: []
                                LoopStartSlc: []
                                     LowPrio: []
                                   MachineID: 'ec349951eef74c84b793fe68b701642e'
                             MagnitudeImages: []
                                MatrixSource: []
                                   MaxMemory: 122680
                      MaxNoOfFilterParamLogs: 3
                              MaxNoOfOutputs: 22
                            MaxNoOfRepTraces: 1
                            MaxRawObjectSize: 96490
                   MaxRawObjectSizePrioRecon: 3150
                                     MeasUID: 751
                                     MeasUid: 751
                                        Mode: 2
                              MultiSliceMode: 2
                               MultiStepProt: 1916
                               MultipleCalls: []
                          MultipleSeriesMode: 4
                               N0F3DFTLength: 52
                             N0FImageColumns: 288
                               N0FImageLines: 256
                          N0FImagePartitions: 48
                               N0FPEFTLength: 256
                                 N0FPhaseFoV: [204.4444 0 0 0 0 0 0 0 0 0 0 0 0 0 … ] (1×128 double)
                               N0FRoFTLength: 576
                                N0FThickness: [144 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 … ] (1×128 double)
                                      NAFLin: 2
                                      NAFPar: 1
                                        NAve: 1
                                    NAveMeas: 1
                              NBaseLen4Slope: -1
                                   NBoundPhs: -1
                                 NChaVirtual: []
                                NCoilSelects: 1
                                 NColDivisor: 8
                                    NColMeas: 576
                        NConfigLinSlopeAhead: []
                       NConfigLinSlopeBehind: []
                                        NEco: 2
                                    NEcoMeas: 2
                                   NFirstLin: 1
                                   NFirstPar: []
                                NFirstRefLin: -1
                                NFirstRefPar: -1
                                    NIdaMeas: 1
                                    NIdbMeas: 1
                                    NIdcMeas: 1
                                    NIddMeas: 1
                                    NIdeMeas: 1
                                  NImageCols: 288
                                  NImageLins: 256
                                   NImagePar: 48
                             NImagesExpected: []
                                        NLin: 111
                                 NLinDivisor: 8
                                    NLinMeas: 223
                                    NPaftLen: 52
                                        NPar: 46
                                 NParDivisor: 8
                                    NParMeas: 46
                              NParSlopePatch: []
                                    NPeFTLen: 256
                                    NPeftLen: 256
                                        NPhs: 1
                                    NPhsMeas: 1
                                    NProtPar: 48
                                    NProtSlc: 1
                         NRawFilterSlope_256: []
                                     NRefLin: 64
                                   NRefLines: 64
                                     NRefPar: 52
                                        NRep: []
                                    NRepMeas: 1
                                    NRoFtlen: 576
                                        NSeg: 1
                                    NSegMeas: []
                                    NSetMeas: 1
                                        NSlc: 1
                                    NSlcMeas: 1
                                    NTrueLin: 111
                                    NTruePar: 46
                             NoImagesPerSlab: 48
                            NoOfFourierLines: 223
                       NoOfFourierPartitions: 46
                         NoOfImaScansPerSlab: []
                  NoOfflineCalcOnAbortedMeas: []
                      NoWarningOnMissingData: []
                               NoiseDecorrOn: 1
                             NoiseReductionI: 1.0000e-04
                            NoiseReductionII: []
                            NoiseScaleFactor: 1.0000e-05
                     NormalizeFactorModerate: 50
                              NormalizeSetup: 2
           NumberOfCutoffValues4EveryReadout: 4
                                NumberOfGPUs: 2
                          NumberOfImageTypes: 2
                          NumberOfProcessors: 20
                              ObjNamWithReps: 1
                                     ObjName: 'RawObj'
                               ObjWithRepDim: []
                               OnlineSendIma: []
                          OnlineSendMeasData: []
                               OnlineSendRAW: []
                               OnlineSendRHP: []
                            OptimalLinLength: 1
                              OverrideMatrix: []
                                 POOLTHREADS: 1
                                     PaFTLen: 52
                             ParSlope4filter: -1
                          ParSlopeLenFromSeq: -1
                                  PatChanged: []
                                 PatPosition: 'HFS'
                PatchValueKSpaceCentreColumn: -1
                  PatchValueKSpaceCentreLine: -1
             PatchValueKSpaceCentrePartition: -1
                                     Patient: 'xxxxxxxxxxxxxx'
                             PatientBirthDay: 'xxxxxxxx'
                                   PatientID: 'xxxxxxxxxxxxxx'
                                 PatientLOID: []
                                 PatientName: 'xxxxxxxxxxx'
                             PatientPosition: 'HFS'
                                  PatientSex: 2
                                       PeFOV: 204.4444
                           PerformAdjustPaFT: 1
                  PerformCutoff4EveryReadout: []
                   PerformCutoffIfFoundInMDH: 1
                          PerformanceCounter: []
                          PhaseEncodingLines: 256
                                    PhaseFoV: 204.4444
                                 PhaseImages: []
                   PhasePartialFourierFactor: 8
                             PhaseResolution: 1
                         PixelBandwidthPhase: []
                          PixelBandwidthRead: []
                         PixelBandwidthSlice: []
                                 PreScanAlgo: 1
                            PrepareTimestamp: [1990 19]
                                PresetRawObj: []
                            PresetRefScanObj: 1
                                     Profile: 2
                               ProtectedSize: 3200
                       ProtocolChangeHistory: []
                                ProtocolName: 'SWI_UKBB_separateREF_still'
                            ProvideChannelId: 1
                             ProvideProgress: 1
                            PtabAbsStartPosZ: -1118
                       PtabAbsStartPosZValid: 1
                                  RAM_Memory: 128
                                    RaidSimu: []
                                      RawAve: 1
                                      RawCha: []
                                      RawCol: 288
                                      RawEco: 2
                                 RawFilterOn: []
                                      RawIda: 1
                                      RawIdb: 1
                                      RawIdc: 1
                                      RawIdd: 1
                                      RawIde: 1
                                      RawLin: 111
                              RawObjsInQuota: []
                                      RawPar: 52
                                      RawPhs: 1
                                      RawRep: 1
                                      RawSet: 1
                                      RawSlc: 1
                                     ReadFoV: 230
                             ReadoutOSFactor: 2
                   ReadoutOversamplingFactor: 2
                            ReadoutsExpected: []
                              RealPartImages: []
                            RecalcWsOnDemand: []
                                  RefObjName: 'RefScanObj'
                                 RefScanMode: 4
                            RefScans4AllDims: []
                            RefScans4AllReps: []
                                ReferenceUid: 741
                                  RegisterID: 19
               RemoveRawObjPerLastScanInMeas: 1
                     RemoveRawObjPerNextRepX: 1
                           ReportDestruction: []
                     ReverseRepOrderInSeries: []
                                       RoFOV: 230
                             RunningOnImager: 1
                         SBCSOriginPositionX: []
                         SBCSOriginPositionY: []
                         SBCSOriginPositionZ: -1102
                               SaveOriginals: []
                              SaveUnfiltered: []
                    ScaleFirstCoilSelectOnly: []
                       ScaleToUnitNoisePower: []
                   SecondsSinceMidnight4Test: []
                            SendDicomForIDEA: []
                     SendKSpaceFilterViaCtrl: []
                         SendNoiseMapViaCtrl: []
                                SendReadouts: []
                                 SensMapName: 741
             SeparateSeriesForFilteredImages: 1
                                SeqDimension: 4
                         SequenceDescription: 'SWI_UKBB_separateREF_still'
                            SequenceFileName: '%SiemensSeq%\gre'
                        SequenceImageComment: []
                              SequenceString: 'swi3d2r'
                           SeriesDescription: []
                                  SeriesLOID: '1.3.12.2.1107.5.2.50.176289.2024102419135123739663910.0.0.0'
                            SetSeriesEndFlag: 1
                   SetSoda4SecondaryCaptured: []
                             SettingsChanged: []
                                 SkipDisplay: []
    SliceGrappaWeightsDescriptionObjectAtDll: []
                       SlidingWindowMemBlock: []
                        SlidingWindowMemSize: 100
                           SlidingWindowSize: 32
                              SmoothingLevel: 3
                      StoreAllRawObjsTillEnd: []
                         StoreEnvObjsTillEnd: []
                                       Study: '1.3.12.2.1107.5.2.50.176289.30000024102409294050200000021'
                                   StudyLOID: '1.3.12.2.1107.5.2.50.176289.30000024102409294050200000021'
                            SubProtocolIndex: []
                         SuppressCompressLin: []
                         SuppressCompressPar: []
                                SuppressSend: []
                            SuppressWarnings: []
               SwitchOffWarning4MissingScans: []
                                          TI: [300000 0 0 0 0 0 0 0 0 0 0 0 0 0 0 … ] (1×256 double)
                               TPATDimension: 16
                                          TR: [27000 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 … ] (1×256 double)
                            TemporalOrdering: []
                                   Threading: []
                       Timeout4QuotaFallback: []
                     TotalScanTimeFromUIinms: []
                                 TriggerMode: 3
                   TriggerRefScanCalculation: []
                         TriggerTimeRequired: []
                          TriggerUseAverages: []
                                 TurboFactor: 1
            UnconditionalEndOfJobCalculation: []
                                  UpsideDown: []
                               UseAllReps4Ws: []
                       UseFirstLastScanFlags: []
                            UseFloatTablePos: []
                           UseRefScans4Image: []
                                   WATERMARK: 16
                                   WsObjName: 'GrappaFindWsWsObj'
                        bCalcMagnitudeImages: 1
                            bCalcPhaseImages: 1
                                 bIsBodyCoil: []
                      bPtabAbsStartPosZValid: 1
                            bUseFirstMapOnly: []
                          bUseSelfCorrection: []
                                calcCoilMaps: []
                                 calcPhasors: 1
                           chronSliceIndices: [0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 … ] (1×256 double)
                                        dCor: []
                                   dFFTScale: []
                  dRawDataCorrectionFactorIm: []
                  dRawDataCorrectionFactorRe: []
                                        dSag: []
                                        dTra: []
                                    distance: []
                                groupIndices: [0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 … ] (1×256 double)
                    iAdaptiveCoilCombineAlgo: 9
                           iPtabAbsStartPosZ: -1118
                     iWeightsWorkaroundDelay: 30000
                                        nCol: 288
                                        nLin: 256
                                      nWsCol: 64
                                      nWsLin: 64
                           phaseOversampling: 2.1738e-12
                                      relFOV: []
                          relPartitionNumber: [1 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 … ] (1×256 double)
                              relSliceNumber: [0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 … ] (1×256 double)
                                sPatPosition: 'HFS'
                                  sPreScanID: 741
                                       shift: []
                                tPatientName: 'xxxxxxxxxxx'
                           tStudyDescription: 'ZN Twins_test'
                                   thickness: []
                               triggerWindow: [0 0 5 0 5 0 0 0 5 0 0 0 0 0 0 0 0 0 … ] (1×32 double)
                            usePVEcorrection: 1
                            x2DInterpolation: []
                                   x_Execute: 1