figure(1); clf;
rng(17371218);
violinSingle(1,randn(1,1000), ...
       'KernelWidth', 0.5, ...
       'withmdn', 1);
violinSingle(0,randn(1,1000) + 6, ...
       'KernelWidth', 0.5, ...
       'Rotation',    'horizontal', ... 
       'side',        'right', ...
       'facecolor',   'r', ...
       'cutoff',      1e-3, ...
       'scaling',     1);
