function save_raw_info(twix_like,hdrConnection,ProjectName,save_tag)
% save_raw_info saves the converted twix-like raw and related sorting
% information in the server for further processing
%   twix-like: twix-like raw generated by the input convertor
%   hdrConnection: connection.header
%   ProjectName: define the saved path, please refer to
%   Framework_config.xml to set related information
%   save_tag: for each reproducible reconstruction method, it should be
%   identify an unique save_tag for sorting

% by Zihan Ning <zihan.1.ning@kcl.ac.uk>
% @King's College London
% 22-May-2025
    fprintf('=========== Saving the raw data to the Server.\n');
    if isfield(hdrConnection,'subjectInformation') && isfield(hdrConnection.subjectInformation,'patientID')           
        patientID = hdrConnection.subjectInformation.patientID;
        save_path = dumpDir_ID(patientID, ProjectName);
    else % cannot find the information 
        save_path = dumpDir_ID([], ProjectName);
    end
    % ZN: to prevent overwriting, the seq name has been renamed as 'seq_name_timestamp'
    hdrConnection = check_overwrite(hdrConnection);
    fileName = hdrConnection.measurementInformation.protocolName;
    twix_like.hdr.fileName = fileName; % ZN: for following writing to prevent overwritting
    twix_like.hdr.save_path = save_path; % to save the result in the same folder
    isRef = contains(fileName, 'REF');
    if isRef
        raw_name = ['RAW_DATA_REF_',fileName,'.mat']; % ZN: the raw data file's name will contain seq_name
        nameRef = fullfile(save_path, raw_name);
    else
        raw_name = ['RAW_DATA_',fileName,'.mat']; % ZN: the raw data file's name will contain seq_name
        nameRef = fullfile(save_path, raw_name);
    end
    save(nameRef, 'twix_like','fileName','-v7.3');
    fprintf('    Raw data saved under the path: %s.\n', nameRef);

    %%% SAVE THE ESSENTIAL INFO COMMUNICATION BETWEEN MAINCALL & SUBCALL
    fprintf('=========== Saving the essential info for communication to Gadgetron Server.\n');
    % ZN: the sorting_info of the data will be saved in a structure and
    % read by the subcall function. For sequences with the same seq type,
    % the early registered data will be processed first
    % after entering the subcall function,the sorting info will be erased
    % from the sorting_info structure to prevent re-reconstruction
    sorting_info = generate_sortinginfo(nameRef,save_path,patientID,fileName,save_tag);
    save(['main_to_sub_',save_tag, '.mat'],'sorting_info');
    fprintf('    Essential info for communication data saved under the path: %s.\n', pwd);

    disp('==============Activating a new matlab window to run subcall function');
end